export const GET_DEFAULT_VALUE = 'GET_DEFAULT_VALUE';
export const GET_DEFAULT_VALUE_SUCCESS = 'GET_DEFAULT_VALUE';
export const GET_DEFAULT_VALUE_FAILURE = 'GET_DEFAULT_VALUE';
export const TEXT_CHANGED = 'TEXT_CHANGED';
export const ADD_BLOCK = 'ADD_BLOCK';
export const REMOVE_BLOCK = 'REMOVE_BLOCK';
